frase = 'Curso de Python para iniciantes'
print(frase.count('o'))
print(len(frase))
print(frase[2:10])
print(frase[::2])
print(frase.find('Android'))
print(frase.lower().find('python'))
print(frase.replace('Python', 'Android'))
print(frase.upper())
print(frase.lower())
print(frase.capitalize())
print(frase.title())
print(frase.split())
print('-'.join(frase))

frase2 = '     Aprenda Python       '
print(frase2)
print(frase2.strip())
print(frase2.lstrip())
print(frase2.rstrip())
